version: '3'
services:
  # By default the gRPC servers are listening at port 8061,
  # according to AI4EU specifications.
  # We can distinguish servers by host, defined by the service name
  # See https://docs.docker.com/compose/networking/
  image-source:
    image: sipgisr/camera-feed-grpc:latest
    environment: 
      CAMERA_URL: "ristmikud.tallinn.ee" 
      REQUEST_URL: "/last/cam055.jpg"
      HTTPS: "True" 
  yolo:
    image: sipgisr/yolov5-grpc:latest
  traffic-routing:
    image: andrejfsantos/traffic-routing:latest
    volumes: 
    - type: bind
      source: ./map_img.png
      target: /workspace/map_img.png
  apply-homog:
    image: andrejfsantos/vision-algorithms:latest
  visualization:
    image: sipgisr/image-visualization:latest
    # Only port visible outside the docker environment
    # to see the images in the web
    ports:
    - 8062:8062
  orchestrator-node:
    image: sipgisr/grpc-orchestrator:latest
    volumes: 
    - type: bind
      source: ./config.yml
      target: /app/config.yml
    environment:
      CONFIG_FILE: "config.yml"
    command: bash -c "java -cp '*' pipeline.orchestrator.App"
